name: 'Set Issue Status'
on:
  # makes this workflow reusable
  workflow_call:
    inputs:
      username:
        description: 'Which username to check if part of org?'
        required: true
        type: string
    outputs:
      is-collaborator: 
        description: "is this login a collaborator?"
        value: ${{ jobs.check-collaborator.outputs.is-collaborator }}

    secrets:
      ADD_TO_TRIAGE_BOARD_TOKEN:
        required: true

jobs:
  check-collaborator:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.ADD_TO_TRIAGE_BOARD_TOKEN }}
    outputs:
      is-collaborator: ${{ steps.is-collaborator.outputs.is-collaborator }}
    steps:
    - name: Check if collaborator
      id: is-collaborator
      run: |
        gh api graphql -f query='
          query($org: String!, $repo: String!, $user: String!) {
            repository(owner: $org, name: $repo) {
              collaborators(query: $user, first: 1) {
                totalCount
              }
            }
          } ' -f org=${{ github.repository_owner }} -f repo=${{ github.event.repository.name }} -f user=${{ inputs.username }} > collaborators.json

        echo 'IS_COLLABORATOR='$(jq -r '.data.repository.collaborators.totalCount' collaborators.json) >> $GITHUB_ENV
        echo env
      
        if [ ${{ env.IS_COLLABORATOR == '0' }} ]; then
          echo "is-collaborator=true" >> $GITHUB_OUTPUT
          echo env
        elif [ ${{ env.IS_COLLABORATOR == '1' }} ]; then
          echo "is-collaborator=false" >> $GITHUB_OUTPUT
          echo env
        fi
