name: 'Triage: add issue/PR to project'

on:
  # makes this workflow reusable
  workflow_call:
    secrets:
      ADD_TO_TRIAGE_BOARD_TOKEN:
        required: true
    inputs:
      check-if-collaborator:
        description: 'Make Collaborator Check'
        default: true
        required: false
        type: boolean
  issues:
    types:
      - opened
  pull_request_target:
    types:
      - opened

jobs:
  check-collaborator:
    runs-on: ubuntu-latest
    steps:
      - name: Check if collaborator
        id: check-collab
        uses: nagash77-cypress/hello-world-javascript-action/.github/workflows/triage_tools_check_if_collaborator.yml@develop
        with:
          username: ${{ github.event.pull_request.user.login || github.event.issue.user.login }}
    outputs:
      is-collaborator: ${{ steps.check-collab.outputs.is-collaborator }}
    
  add-to-triage-project:
    name: Add to triage project
    runs-on: ubuntu-latest
    permissions:
      issues: write
    env:
      PROJECT_NUMBER: 1
      GITHUB_TOKEN: ${{ secrets.ADD_TO_TRIAGE_BOARD_TOKEN }}
    needs: check-collaborator
    #if: ${{ needs.check-collaborator.outputs.is-collaborator == 'false' }}
    steps:
      - name: Output Run Data
        run: |
          echo "${{ toJSON(needs.check-collaborator.outputs) }}"
          echo "${{ toJSON(env) }}"
      - uses: actions/add-to-project@v0.4.0
        # only add issues/prs from outside contributors to the project
        if: ${{ env.IS_COLLABORATOR == 0 }}
        with:
          project-url: https://github.com/orgs/${{github.repository_owner}}/projects/${{env.PROJECT_NUMBER}}
          github-token: ${{ secrets.ADD_TO_TRIAGE_BOARD_TOKEN }}
     
      - uses: actions/github-script@v6
        # only add label to issue for outside contributors
        if: ${{ env.IS_COLLABORATOR == 0 }}
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["triage"]
            })
