name: 'Triage: closed issue comment'
on:

  issue_comment:
    types: [created]

jobs:
  handle-comment-scenarios:
    needs: get-data-about-issue-and-project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Run triage script
        run: |
          cd scripts/triage
          node comment_workflow.js
        env:
          GITHUB_TOKEN: ${{ secrets.ADD_TO_TRIAGE_BOARD_TOKEN }}
          BOARD_ID: 1
          ORG_NAME: 'nagash77-cypress'
          PROJECT_ID: ${{ needs.get-data-about-issue-and-project.outputs.project_id }}
          PROJECT_ITEM_ID: ${{ needs.get-data-about-issue-and-project.outputs.project_item_id }}
          STATUS_FIELD_ID: ${{ needs.get-data-about-issue-and-project.outputs.status_field_id }}
          PROJECT_STATUS: ${{ needs.get-data-about-issue-and-project.outputs.project_status }}
          NEW_ISSUE_OPTION_ID: ${{ needs.get-data-about-issue-and-project.outputs.new_issue_option_id }}
  
  