name: 'Add stale issue/PR to Triage Board'
on:
  issue_comment:
    types: [created]

jobs:
  check-collaborator:
    if: >-
      (
        contains(github.event.pull_request.labels.*.name, 'stale') || 
        contains(github.event.issue.labels.*.name, 'stale')
      )
    name: Check if collaborator
    uses: nagash77-cypress/hello-world-javascript-action/.github/workflows/triage_tools_check_if_collaborator.yml@develop
    with:
      username: ${{ github.event.pull_request.user.login || github.event.issue.user.login }}
    secrets: inherit

  add-to-triage-project-board:
    needs: check-collaborator
    if: >-
      (
        (contains(github.event.pull_request.labels.*.name, 'stale') || contains(github.event.issue.labels.*.name, 'stale')) &&
        needs.check-collaborator.outputs.is-collaborator == 'false'
      )
    uses: nagash77-cypress/hello-world-javascript-action/.github/workflows/triage_add_to_project.yml@develop
    secrets: inherit
  update-status-to-awaiting-response:
    needs: add-to-triage-project-board
    uses: nagash77-cypress/hello-world-javascript-action/.github/workflows/triage_update_status.yml@develop
    with:
      status: 'Awaiting Response'
    secrets: inherit