name: 'Triage: closed issue comment'
on:

  issue_comment:
    types: [created]

jobs:
  handle-comment-scenarios:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Run triage script
        run: |
          cd scripts/triage
          node comment_workflow.js
        env:
          GITHUB_TOKEN: ${{ secrets.ADD_TO_TRIAGE_BOARD_TOKEN }}
          