name: 'Set Issue Status'
on:
  # makes this workflow reusable
  workflow_call:
    inputs:
      username:
        description: 'Which username to check if part of org?'
        required: true
        type: string

    secrets:
      ADD_TO_TRIAGE_BOARD_TOKEN:
        required: true

jobs:
  check-collaborator:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.ADD_TO_TRIAGE_BOARD_TOKEN }}
    outputs:
      is-collaborator: ${{ steps.is-collaborator.outputs.is-collaborator }}
    steps:
    - name: Check if collaborator
      id: is-collaborator
      run: |
        gh api graphql -f query='
          query($org: String!, $repo: String!, $user: String!) {
            repository(owner: $org, name: $repo) {
              collaborators(query: $user, first: 1) {
                totalCount
              }
            }
          } ' -f org=${{ github.repository_owner }} -f repo=${{ github.event.repository.name }} -f user=${{ inputs.username }} > collaborators.json

        if [[ $(jq -r '.data.repository.collaborators.totalCount' <<< "$result") -eq 1 ]]; then
          echo "is-collaborator=true" >> $GITHUB_OUTPUT
        else
          echo "is-collaborator=false" >> $GITHUB_OUTPUT
        fi
