name: 'Handle creation of new issue or PR'

on:

  # makes this workflow reusable
  workflow_call:
    secrets:
      ADD_TO_TRIAGE_BOARD_TOKEN:
        required: true

  issues:
    types:
      - opened
  pull_request_target:
    types:
      - opened

jobs:
  handle-comment-scenarios:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: develop
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Run comment_workflow.js Script
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ADD_TO_TRIAGE_BOARD_TOKEN }}
          script: |
            const script = require('./scripts/triage/item_creation_workflow.js')
            script.handleItemCreation(github, context);
          